### ISSUE TITLE
有个BUG，不知道该怎么解决

### ISSUE THREAD

**Issue by yaozifan** [housenkui/JavascriptBridge#2]
目前用的WKWebView，在调用：[_bridge callHandler:@"replaceimage%@,%@" data:[self replaceUrlSpecialString:info.src] responseCallback:^(id responseData) {
               NSLog(@"ObjC received response: %@", responseData);
           }]；
这句话的时候，block并不会回调，也就是说这句话没有执行成功，换到我的项目里就是图片不能加载出来，而如果使用webView的话，就可以正常加载出图片，block也会回调，这个问题不止在你这里出现，在WebViewJavascriptBridge这个框架里也有这个问题

**Comment by housenkui** [comment]
您好，Demo可以吗？

**Comment by housenkui** [comment]
业务代码没有处理好。
